config/routes.rb
Rails.application.routes.draw do
  get 'books/edit'
  devise_for :users
  get 'users' => "users#index"
  root to: "homes#top"
  get 'home/about' => "homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :index, :show, :destroy]
  get 'books/destroy'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :edit, :update]
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    
  validates :title, presence: true
  validates :body, presence: true,
  length: { maximum: 200 }
  
  

  
  def get_book
    unless book.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, {presence: true,
                    length: { minimum: 2, maximum: 20, message: "is too short (minimum is 2 characters)"},
                    uniqueness: {message: "既に同じユーザー名があります。"}}

  
  validates :introduction,
  length: { maximum: 50 }
         
  has_many :books ,dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected
  
  protect_from_forgery

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def new
    @books = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
     if @book.save
       redirect_to @book, notice: 'successfully'
     else 
       @books = Book.all
       render :index
     end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @newbook = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'successfully'
    else
      render :edit
    end  
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = @user.books
  end
  
  def create
    @user = User.find(params[:id])
    @books = @user.books
    if @user.save
     redirect_to @user, notice: 'successfully'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      @books = @user.books
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
     redirect_to @user, notice: 'successfully'
    else
     render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<% @books.each do |book| %>
<p id="notice"></p>
<h2>User information</h2>
<div class="col-lg-4"></div>
  <p>投稿ユーザー画像：<%= image_tag current_user.get_profile_image(100,100) %></p>
<h2>New book</h2>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
<%= f.submit 'Create Book', class: "btn btn-secondary" %>
<div class="container">
 <div class="row">
  <div class="col-lg-4"> 
<table class="table table-striped"></table>
  </div>
 </div>
</div>
  <% end %>
<h2>Book detail</h2>
<% @books.each do |book| %>

  <p>Title</p>
  <div class="col-lg-4"></div>
  <span><%= book.title %></span>
  <p>Opinion</p>
  <span><%= book.body %></span>
<% end %>

<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <%= image_tag book.get_image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag book.user.get_profile_image(100,100) %></p>
  <p>ショップ名：<%= book.book_name %></p>
  <p>説明：<%= book.caption %></p>
  <p>ユーザーネーム：<%= book.user.name %></p>
</div>
<% end %>
<%= render 'books/book', books: @books %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<p id="notice">
    <%= notice %>
</p>

<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<h4>Title</h4>
<%= f.text_field :title %>
  
<h4>Opinion</h4>
<%= f.text_area :body %>
  
<%= f.submit 'Update Book' %>
  
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
    

<div class="row">
  <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary", method: :get do %>
   　<i class="fas fa-user-cog"></i>  
  <% end %>
</div>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
<%= f.submit 'Create Book', class: "btn btn-secondary" %>
  <% end %>
   </div>
   
    <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colespan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
 </div>
</div>
<% @books.each do |book| %>
<%= link_to(book.user) do %>
<%= image_tag book.user.get_profile_image(100,100) %>
<% end %>

  <p>Title</p>
  <%= link_to book.title, book_path(book.id) %>
  <p>Opinion</p>
  <span><%= book.body %></span>
<% end %>

app/views/books/new.html.erb
<h2>User information</h2>
  <p>投稿ユーザー画像：<%= image_tag bookers.user.get_profile_image(100,100) %></p>
<h2>New book</h2>
  <%= form_with model: @book do |f| %>
    <h4>Image</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>Title</h4>
      <%= f.text_field :shop_name %>
    <h4>Opinion</h4>
      <%= f.text_area :caption %>
    <%= link_to 'New Book', new_book_path, class: "btn btn-secondary" %>
  <% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
          <th>name</th>
          <th><%= @user.name %></th>
          </tr>
          <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

  <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary", method: :get do %>
   　<i class="fas fa-user-cog"></i>  
  <% end %>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: @newbook do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
<%= f.submit 'Create Book', class: "btn btn-secondary" %>
  <% end %>
  </div>
  
      <div class="col-md-8 offset-md-1">
<h1>Book detail</h1>
  <p>Title:<%= @book.title %></p>
  <p>Opinion：<%= @book.body %></p>
  <p>Image：<%= link_to image_tag @book.user.get_profile_image(100,100) %></p>  
  <p>ユーザーネーム：<%= link_to @book.user.name, user_path(@user.id) %></p>
  <%= link_to user_path(@user.id) %>
  <% if user_signed_in? && @book.user == current_user %>
    <%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
    <%= link_to "Edit", edit_book_path(@book.id) %>
  <% end %>
     </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i>Bookers!</h1>
    </div>
</div>

app/views/homes/top.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
        </div>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-info" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Home', user_path(current_user.id), class: 'nav-link text-dark' %>
              <i class="fas fa-home"></i>
            </li>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: 'nav-link text-dark' %>
              <i class="fas fa-users"></i>
            </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'nav-link text-dark' %>
              <i class="fas fa-book-open"></i>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
              <i class="fas fa-sign-out-alt"></i>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link text-dark' %>
              <i class="fas fa-home"></i>
            </li>
            <li class="nav-item">
              <%= link_to 'About', home_about_path, class: 'nav-link text-dark' %>
              <i class="fas fa-link"></i>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-dark' %>
              <i class="fas fa-user-plus"></i>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark' %>
              <i class="fas fa-sign-in-alt"></i>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"introduction"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
          <td>name</td>
          <td><%= @user.name %></td>
          </tr>
          <tr>
          <td>introduction</td>
          <td><%= @user.introduction %></td>
          </tr>
        </tbody>
      </table>
  
  <div class="row">
  <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary", method: :get do %>
   　<i class="fas fa-user-cog"></i>  
  <% end %>
  </div>

  <p>投稿ユーザー画像：<%= link_to image_tag current_user.get_profile_image(100,100) %></p>
<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @book do |f| %>
  <div class="form-group">
    <td>Title</td>
      <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <td>Opinion</td>
      <%= f.text_area :body %>
  </div>
<%= f.submit 'Create Book', class: "btn btn-secondary" %>
  <% end %>
   </div>
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <td>image</td>
      <td>name</td>
      <td colspan="3"></td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
</div>
  </tbody>
</table>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice">
 <%= notice %>
</p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100,100) %>
 <table class="table">
  <tbody>
  <tr>
	  <td>name</td>
	  <td><%= @user.name %></td>
  </tr>
  <tr>
	  <td>introduction</td>
	  <td><%= @user.introduction %></td>
  </tr>
  </tbody>
 </table>
　
<div class="row">
  <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary", method: :get do %>
   　<i class="fas fa-user-cog"></i>  
  <% end %>
</div>
      <h2 class="mt-3">New book</h2>
      <form action="/books" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="qf5pOsqyPFWoy_NrYxA6GzO7LLcGhObD-szQR9iR6l6JF1e2valD4IpSFwa1-ovOZOqlSq25UGQITjdYxZHGyQ" autocomplete="off">
  <div class="form-group">
    <label for="book_title">Title</label>
    <input class="form-control book_title" type="text" name="book[title]" id="book_title">
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
  </div>
  <div class="form-group">
    <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
  </div>
</form>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td></td>
      </tr>
      <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <p><%= link_to "Update User", @user %></p>
</div>

<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag book.user.get_profile_image(100,100) %></p>
  <p>ユーザーネーム：<%= book.user.name %></p>
</div>
<% end %>
<%#= render 'books/book', books: @books %>